require 'rubyrati/base'          #0.0.1 milestone
require 'rubyrati/cosmos'        #0.0.2 milestone
require 'rubyrati/search'        #0.0.3 milestone
require 'rubyrati/tag'           #0.0.4 milestone
require 'rubyrati/dailycounts'   #0.0.5 milestone
require 'rubyrati/toptags'       #0.0.6 milestone
require 'rubyrati/bloginfo'      #0.0.7 milestone
require 'rubyrati/blogposttags'  #0.0.8 milestone
require 'rubyrati/getinfo'       #0.0.9 milestone