require 'base'          #0.0.1 milestone
require 'cosmos'        #0.0.2 milestone
require 'search'        #0.0.3 milestone
require 'tag'           #0.0.4 milestone
require 'dailycounts'   #0.0.5 milestone
require 'toptags'       #0.0.6 milestone
require 'bloginfo'      #0.0.7 milestone
require 'blogposttags'  #0.0.8 milestone
require 'getinfo'       #0.0.9 milestone